/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Answer = string;
export type Kind = "bbox" | "mask" | "overlay" | "table" | "none";
export type XMin = number;
export type YMin = number;
export type XMax = number;
export type YMax = number;
export type Label = string | null;
export type Score = number | null;
/**
 * Which image in ToolRequest.images this refers to
 */

export type ImageIndex = number;
export type Boxes = BoundingBox[];
/**
 * Single-band raster, 0/1 or class-indexed
 */
export type MaskPath = string | null;
/**
 * Rendered PNG for display in the UI
 */
export type OverlayPng = string | null;
/**
 * Georeferenced geometries for the downloadable report
 */
export type Geojson = {
  [k: string]: unknown;
} | null;
/**
 * Short description of what is shown
 */
export type Caption = string | null;
export type Confidence = number;
export type ConfidenceMethod = string;
/**
 * Coarse task family, decided deterministically from the inputs alone.
 *
 * The controller's first stage picks one of these by counting and inspecting
 * images — no LLM involved. The second stage picks a specific tool within it.
 */
export type TaskFamily = "single_image" | "bi_temporal" | "cross_modal";
/**
 * The specific task a tool performs. One tool per name.
 */
export type TaskName = "vqa" | "grounding" | "captioning" | "change_vqa" | "fusion";
export type ToolsUsed = TaskName[];
export type Step = number;
export type Stage = "validate" | "classify" | "route" | "execute" | "combine";
export type Detail = string;
export type ModelId = string | null;
export type DurationMs = number;
export type Trace = TraceStep[];
export type Ok = boolean;
export type Severity = "error" | "warning" | "info";
/**
 * Stable machine-readable code, e.g. 'crs_mismatch'
 */
export type Code = string;
/**
 * Human-readable, shown to the user
 */
export type Message = string;
export type ImageIndex1 = number | null;
export type Issues = ValidationIssue[];
export type TotalLatencyMs = number;
export type RequestId = string | null;

/**
 * The complete API response: answer, evidence, and how we got there.
 */
export interface QueryResponse {
  answer: Answer;
  evidence: Evidence;
  confidence: Confidence;
  confidence_method: ConfidenceMethod;
  task_family: TaskFamily;
  tools_used?: ToolsUsed;
  trace?: Trace;
  validation: ValidationReport;
  total_latency_ms?: TotalLatencyMs;
  request_id?: RequestId;
  [k: string]: unknown;
}
/**
 * The visual backing for an answer.
 *
 * `kind == "none"` is legitimate and expected — a yes/no VQA answer has no
 * region to point at. It is not a failure state.
 */
export interface Evidence {
  kind?: Kind;
  boxes?: Boxes;
  mask_path?: MaskPath;
  overlay_png?: OverlayPng;
  geojson?: Geojson;
  legend?: Legend;
  caption?: Caption;
  [k: string]: unknown;
}
/**
 * A box in pixel coordinates of the referenced image.
 *
 * Pixel space, not normalised, not geographic. The report layer converts to
 * geographic coordinates using the image transform when one exists.
 */
export interface BoundingBox {
  x_min: XMin;
  y_min: YMin;
  x_max: XMax;
  y_max: YMax;
  label?: Label;
  score?: Score;
  image_index?: ImageIndex;
  [k: string]: unknown;
}
/**
 * Class value -> human-readable label, for masks
 */
export interface Legend {
  [k: string]: string;
}
/**
 * One observable step in the execution trace.
 *
 * Only this is evaluated by the judges — internal LLM reasoning text is neither
 * required nor scored. Keep it factual.
 */
export interface TraceStep {
  step: Step;
  stage: Stage;
  detail: Detail;
  tool_name?: TaskName | null;
  model_id?: ModelId;
  params?: Params;
  duration_ms?: DurationMs;
  [k: string]: unknown;
}
export interface Params {
  [k: string]: unknown;
}
export interface ValidationReport {
  ok: Ok;
  issues?: Issues;
  [k: string]: unknown;
}
export interface ValidationIssue {
  severity: Severity;
  code: Code;
  message: Message;
  image_index?: ImageIndex1;
  [k: string]: unknown;
}

